Algoritmo "Lista"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/10/2021
Var
produto : vetor [0..9] de caractere
cont : inteiro

Inicio
para cont de 0 ate 9 faca
   escreval("Escreva o nome do produto")
   leia(produto[cont])
fimpara

escreval()
escreval("Os produtos são :")

para cont de 0 ate 9 faca
   escreval(produto[cont])
fimpara
escreval()


Fimalgoritmo